### ISSUE TITLE
Weapon fonts don't load on Weapon Kills tab of stats page

### ISSUE THREAD

**Issue by jsbento** [camerontredoux/vexcollective#2]
cors blocks weapon fonts

Access to font at 'webpack:///mini-css-extract-plugin/_next/static/media/Destiny_Keys.a45f2ca5.otf' from origin 'https://vexcollective.com/' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https, isolated-app.

**Comment by camerontredoux** [comment]
Solved, needed to put fonts in public folder for vercel to load it correctly
